### ISSUE TITLE
Filter only project directories

### ISSUE THREAD

**Issue by ghost** [doblak/ps-clean#1]
I have an issue with a project that uses folder named "bin" for other purposes (it's actually a part of javascript assets).
Can you make the script remove "bin" and "obj" folders only in top level .NET project directories (they always contain *.csproj / *.vbproj files)?

**Comment by doblak** [comment]
I overlooked your question unfortunately. You probably solved this long ago.

Some projects might have output folders set to other locations and there may be build scripts used that put files to some subfolder structure - such feature would be too restrictive for general use.

Thanks for the suggestion.
